export const AUTH_MESSAGES = {
	WRONG_EMAIL_OR_PASSWORD: "Email hoặc mật khẩu không đúng",
	USER_NOT_FOUND: "Không tìm thấy người dùng",
	LOGIN_SUCCESS: "Đăng nhập thành công",
	REGISTER_SUCCESS: "Đăng ký thành công",
	REFRESH_TOKEN_SUCCESS: "Làm mới token thành công",
	FORGOT_PASSWORD_SUCCESS: "Đã gửi email đặt lại mật khẩu",
	RESET_PASSWORD_SUCCESS: "Đặt lại mật khẩu thành công",
	FAILED_TO_FETCH_GOOGLE_TOKEN: "Không thể lấy token từ Google",
	EMAIL_NOT_VERIFIED: "Email chưa được xác minh",
	LOGOUT_SUCCESS: "Đăng xuất thành công",
	INVALID_REFRESH_TOKEN: "Refresh token không hợp lệ",
};
export const MESSAGE = {
	NOT_FOUND: "Không tìm thấy",
	INTERNAL_SERVER_ERROR: "Lỗi máy chủ nội bộ",
	INVALID_EMAIL: "Lỗi định dạng email",
	INVALID_PASSWORD: "Mật khẩu từ 6 đến 100 ký tự, phải chứa ký tự đặc biệt và số",
	USERNAME_REQUIRED: "Tên người dùng là bắt buộc",
	USERNAME_MAX_LENGTH: "Tên người dùng phải có tối đa 50 ký tự",
	VALIDATION_ERROR: "Lỗi xác thực dữ liệu",
	ACCESS_TOKEN_REQUIRED: "Access token không được để trống",
	REFRESH_TOKEN_REQUIRED: "Refresh token không được để trống",
	INVALID_CREDENTIALS: "Thông tin đăng nhập không hợp lệ",
	UNAUTHORIZED: "Truy cập không được phép",
	FORBIDDEN: "Truy cập bị cấm",
	TOKEN_REQUIRED: "Token không được để trống",
};
